### ISSUE TITLE
transformEntries({ from: ['id'],... }) yields error rather than usable id

### ISSUE THREAD

**Issue by VanDoornP** [contentful/contentful-migration#1170] opened 2023-01-27 10:43 UTC
## Expected Behavior
I expect to be able to use the entry 'id' when I leverage`transformEntries`. For example:
```
  const migrationFunction = (migration) => {
    migration.transformEntries({
      contentType: 'myContentType',
      from: ['id'],
      to: ['fieldToTransform'],
      transformEntryForLocale(fromFields, currentLocale) {
        // Do stuff to update 'fieldToTransform'
      },
    });
  };
```

## Actual Behavior
I get an error in return:
```You cannot transform entries for content type "myContentType" because "id" can't be found on it.```

I have tried id, entryId, entry_id, contentfulId, contentful_id, _id, and sys.id. None of them worked.

## Possible Solution
Ensure the field 'id' can also be used, just like the other fields; or improve documentation if it's already possible.

## Context
I have a list of article entries I want to assign to pre-defined categories. `{ [articleId: string]: string }`. I can't do that unless I can obtain the id from the `fromFields` variable.

## Environment
-   **Node Version**: v18.12.1
-   **Package Manager Version**: v8.19.2
-   **Operating System**: #64~20.04.1-Ubuntu
-   **Package Version**: ?

**Comment by VanDoornP** [comment] 2023-02-10 10:40
Anyone?

**Comment by PierreCavalet** [comment] 2023-05-25 13:28
@VanDoornP I think it's a duplicate of my issue here: #1029 

I opened a PR. you won't be able to access it as of now, just so you know.

**Comment by marcolink** [comment] 2023-06-07 11:22
This has bee implemented: https://github.com/contentful/contentful-migration/releases/tag/v4.13.0

**Closed by marcolink** 2023-06-07 11:22 UTC
