### ISSUE TITLE
Editor interface for UI-Extensions is deleted when you run another migration

### ISSUE THREAD

**Issue by amartinm7** [contentful/contentful-migration#78] opened 2018-03-06 15:02 UTC
The first time you run the migration tool for attaching your own ui-extension to a field, everything is working well. The appearance tab for this field shows the ui-extension attached/marked well. The problem is when you run the migration tool another time with another script in the same content type, then the editor interface settings is removed. If you go back to the appearance tab for that field, the ui-extension is not selected well.

Regards!

**Comment by kalverk** [comment] 2018-03-21 07:24
Example

First we create a content type
```
module.exports = function (migration) {
    const myContentType = migration.createContentType("myContentType");
    myContentType.name("myContentType");
    myContentType.description("My Content Type");
    myContentType.displayField("name");

    myContentType
        .createField("name")
        .name("Name")
        .type("Symbol")
        .required(true);
};
```
Next we change appearance to UI-extension
```
module.exports = function (migration) {
    migration
        .editContentType("myContentType")
        .changeEditorInterface("name", "myUIExtension");
};
```
Now appearance is correct in contentful ui, but after running the next migration script
```
module.exports = function (migration) {
    const myContentType = migration.editContentType("myContentType");

    myContentType
        .editField("name")
        .required(false);
};
```
the appearance link in the contentful ui disappears

**Comment by jesustalaveragomez** [comment] 2018-04-05 07:33
Hi,

I'm having the same issue. Are you planning to fix it?

Thank you. 
Regards

**Comment by Soliah** [comment] 2018-05-25 02:42
I believe this actually occurs whether you're using a UI extension or not. Whenever we run migrations against a content type, we find some fields lose their helptext and display settings.

**Comment by Khaledgarbaya** [comment] 2018-05-25 08:08
Hey there,
I will investigate this asap and get back to you.

Best,
Khaled

**Comment by Soliah** [comment] 2018-06-01 01:59
@Khaledgarbaya any results from your investigation? We've now become extremely cautious about running this even though it was recommended to us to use.

**Comment by Khaledgarbaya** [comment] 2018-06-01 09:03
Hi @Soliah,
This is indeed a bug when a field is edited the editor interface data is not copied along.
We'll try to fix this asap

Best,
Khaled

**Comment by gurpreetb** [comment] 2018-06-14 14:17
Hi @Khaledgarbaya 

are there any updates on this, we have found the help text doesnt copy over aswell when trying to run migration through the migration-cli.

Thanks

**Comment by Khaledgarbaya** [comment] 2018-06-14 14:50
Hi @gurpreetb,
This issue is high in our priority list and we'll get to it soon.
Best,
Khaled

**Comment by Khaledgarbaya** [comment] 2018-06-27 12:56
Hi @gurpreetb @Soliah @jesustalaveragomez @amartinm7,

I am working on this issue and I tried different scenario but I am not able to reproduce the issue.
Would you mind providing your migration code? also more information.

Best,
Khaled

**Comment by jesustalaveragomez** [comment] 2018-06-27 14:50
Hi @Khaledgarbaya ,

have you tried the scenario that @kalverk sent? It's the same problem that I have

Regards

**Comment by Khaledgarbaya** [comment] 2018-06-27 15:21
@jesustalaveragomez yes I did and the help text did not change.

**Comment by Khaledgarbaya** [comment] 2018-06-27 16:23
Hey @kalverk,
> Script 3 - We modify the same field
Does this include changing a field id or just what you showed in the example?

**Comment by Khaledgarbaya** [comment] 2018-06-29 13:31
Unfortunately, I was not able to reproduce the issue using the above script. I will keep testing different scenarios and get back to you, Apologies for any inconvenience 😞

**Comment by Khaledgarbaya** [comment] 2018-07-02 08:00
I made a small video trying to reproduce the issue, https://youtu.be/QfTKODka8Aw
But this was made with a newish space so it could be related to a wrong state on the space?

**Comment by kalverk** [comment] 2018-07-03 06:42
Hi!

I tried to reproduce it in a new space, but could not. Although I found a similar case where it did not work.

This is no longer a minimum example, it's step by step what we do.

v1.0.0
```
module.exports = function (migration) {
    const myContentType = migration.createContentType("myContentType");
    myContentType.name("My Content Type");
    myContentType.description("My Content Type");
    myContentType.displayField("name");

    myContentType
            .createField("name")
            .name("Name")
            .type("Symbol")
            .localized(false)
            .required(true)
            .disabled(false)
            .omitted(false);

    myContentType
            .createField("externalLink")
            .name("External Link")
            .type("Symbol")
            .localized(true)
            .required(true)
            .disabled(false)
            .omitted(false);

    myContentType
            .createField("myLinkField")
            .name("My Link Field")
            .type("Link")
            .linkType("Entry")
            .localized(false)
            .required(true)
            .disabled(false)
            .omitted(false)
            .validations([
                {
                    "linkContentType": [
                        "myLinkField"
                    ]
                }
            ]);

    myContentType
            .createField("myOtherLinkField")
            .name("My Other Link Field")
            .type("Link")
            .linkType("Entry")
            .localized(true)
            .required(true)
            .disabled(false)
            .omitted(false)
            .validations([
                {
                    "linkContentType": [
                        "myOtherLinkField"
                    ]
                }
            ]);

};
```

v.1.0.1
```
module.exports = function (migration) {
    migration
        .editContentType("myContentType")
        .changeEditorInterface("name", "singleLine")
        .changeEditorInterface("myLinkField", "entryCardEditor");
};
```

v1.0.2
```
module.exports = function (migration) {
    const myContentType = migration.editContentType("myContentType");

    myContentType.deleteField("myLinkField");

    myContentType
        .createField("myLinkField")
        .name("My Link Field")
        .type("Object")
        .localized(false)
        .required(true)
        .disabled(false)
        .omitted(false);
};
```
v1.0.3
```
module.exports = function (migration) {
    migration
        .editContentType("myContentType")
        .changeEditorInterface("myLinkField", "sharedMedia");
};
```

v1.0.4
```
module.exports = function (migration) {
    const myContentType = migration.editContentType("myContentType");

    myContentType
        .editField("externalLink")
        .required(false);

    myContentType
        .editField("myOtherLinkField")
        .required(false);
};```

v1.0.5
```
module.exports = function (migration) {
    const myContentType = migration.editContentType("myContentType");

    myContentType
        .editField("myOtherLinkField")
        .localized(false);
};
```

I ran these 5 scripts sequentially and after finishing the appearance of _myLinkField_ is Object (default), but expected is _sharedMedia_ as defined in the script v1.0.3.

**Comment by Khaledgarbaya** [comment] 2018-08-15 09:16
Hey @kalverk ,

The issue should be fixed from our side, Please let me know if you are still having some issue.

Best,
Khaled

**Closed by Khaledgarbaya** 2018-08-15 09:16 UTC
Labels: bug

**Comment by watsonhamblin** [comment] 2019-01-09 00:09
@Khaledgarbaya we're still having the same issue. Do we need to update anything to get the fix? From the discussion seems like it was only a backend change.

**Comment by jesustalaveragomez** [comment] 2019-01-09 07:34
It works for me using the latest version
